server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ElioMS/config-service.git
  security:
    user:
      name: root
      password: secret

